((emacs-lisp-mode . ((fill-column . 80)
                     (indent-tabs-mode . nil)
                     (sentence-end-double-space . t)
                     (eval . (put 'if-let* 'lisp-indent-function 1))
                     (elisp-lint-indent-specs . ((if-let* . 1)
                                                 (mcp-server-lib-test--with-server . defun)
                                                 (mcp-server-lib-test--with-tools . 1)
                                                 (mcp-server-lib-test--with-undefined-function . 1)
                                                 (mcp-server-lib-test--successful-req . defun)
                                                 (mcp-server-lib-test--verify-req-success . defun)
                                                 (mcp-server-lib-test--with-error-tracking . 1)
                                                 (cl-defstruct . nil)))))))