;; -*- mode: eask; lexical-binding: t -*-

(package "mcp-server-lib"
         "0.1.0"
         "Model Context Protocol server library")

(author "Laurynas Biveinis" "laurynas.biveinis@gmail.com")
(license "GPLv3")
(website-url "https://github.com/laurynas-biveinis/mcp-server-lib.el")
(keywords "comm" "tools")

(package-file "mcp-server-lib.el")
(files "mcp-server-lib-commands.el"
       "mcp-server-lib-metrics.el"
       "mcp-server-lib-ert.el"
       "emacs-mcp-stdio.sh")

(script "test" "eask test ert mcp-server-lib-test.el")

(source "gnu")

(depends-on "emacs" "27.1")
