;;; mcp.el-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mcp-server-lib.el

(register-definition-prefixes "mcp-server-lib" '("mcp-server-lib-"))


;;; Generated autoloads from mcp-server-lib-test.el

(register-definition-prefixes "mcp-server-lib-test" '("mcp-server-lib-test--"))


;;; Generated autoloads from mcp-server-lib-test-bytecode-handler.el

(register-definition-prefixes "mcp-server-lib-test-bytecode-handler" '("mcp-server-lib-test-bytecode-handler--handler"))


;;; Generated autoloads from mcp-server-lib-commands.el

(autoload 'mcp-start "mcp-server-lib-commands" "\
Start the MCP server and begin handling client requests.
This is a convenience alias for `mcp-server-lib-start'." t)
(autoload 'mcp-stop "mcp-server-lib-commands" "\
Stop the MCP server from processing client requests.
This is a convenience alias for `mcp-server-lib-stop'." t)


;;; End of scraped data

(provide 'mcp.el-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mcp.el-autoloads.el ends here
